### ISSUE TITLE
Issue installing software: "UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage."

### ISSUE THREAD

**Issue by HenryCarr98** [snap-stanford/KGWAS#2]
I would like to install a package called KGWAS and run its demo code https://github.com/snap-stanford/KGWAS/blob/master/demo/kgwas_101.ipynb. I have installed it and all its dependencies , however, when I test it, it always returns me with an error message (attached below). Would you please help me with this issue?

Thank you very much!

```
python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('../')
>>>
>>> from kgwas import KGWAS, KGWAS_Data
/home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/torch_sparse/_convert_cpu.so: undefined symbol: __kmpc_fork_call
warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/kgwas/_init_.py", line 2, in <module>
from .kgwas import KGWAS
File "/home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/kgwas/kgwas.py", line 22, in <module>
from .model import HeteroGNN
File "/home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/kgwas/model.py", line 7, in <module>
from .conv import GATConv
File "/home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/kgwas/conv.py", line 7, in <module>
from torch_sparse import SparseTensor, set_diag
File "/home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/torch_sparse/_init_.py", line 18, in <module>
torch.ops.load_library(spec.origin)
File "/home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
ctypes.CDLL(path)
File "/home/.conda/envs/kgwas_gpu/lib/python3.10/ctypes/_init_.py", line 374, in _init_
self._handle = _dlopen(self._name, mode)
OSError: /home/.conda/envs/kgwas_gpu/lib/python3.10/site-packages/torch_sparse/_convert_cpu.so: undefined symbol: __kmpc_fork_call
>>> data = KGWAS_Data(data_path = './data/')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'KGWAS_Data' is not defined
>>> data.load_kg()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'data' is not defined
```

**Comment by HenryCarr98** [comment]
Hello, just pinging this issue to see if there are any updates? Cheers.

**Comment by HenryCarr98** [comment]
Hello! Yes I can confirm I followed those linked instructions. This is what I get when I import torch-sparse. And yes, I double checked and openMP is enabled. 

```
python -c "import torch; print(torch.__version__)"
2.5.1+cu124
```

**Comment by kexinhuang12345** [comment]
i see - can you try `from torch_sparse import coalesce`?

**Comment by HenryCarr98** [comment]
Hi, doing so returns 

```
python -c "from torch_sparse import coalesce"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch_sparse/__init__.py", line 39, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch_sparse/storage.py", line 7, in <module>
    from torch_sparse.utils import Final, index_sort
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch_sparse/utils.py", line 5, in <module>
    import torch_sparse.typing
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch_sparse/typing.py", line 2, in <module>
    import pyg_lib  # noqa
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pyg_lib/__init__.py", line 34, in <module>
    load_library('libpyg')
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/pyg_lib/__init__.py", line 31, in load_library
    torch.ops.load_library(spec.origin)
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/home/username/rds/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /rds/user/username/hpc-work/miniconda3/envs/pytorch2/lib/python3.10/site-packages/libpyg.so)
```

**Comment by kexinhuang12345** [comment]
yes, looks like the pyg is not installed correctly. can you try re-install the pyg and related package? you can use the pip version, which i personally found it more bug-free. 

For example, you will need to make sure that the pytorch, OS, and cuda version match with what you have. 

For example, for pytorch 2.5, linux and cuda = 12.4, install pytorch first and then do:

pip install torch_geometric
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.5.0+cu124.html

**Comment by HenryCarr98** [comment]
I also ran 

```bash
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jul_14_19:41:19_PDT_2021
Cuda compilation tools, release 11.4, V11.4.100
Build cuda_11.4.r11.4/compiler.30188945_0
```
And

```bash
gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

as well as 

```bash
ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Let me know if any of this helps.

**Comment by kexinhuang12345** [comment]
yeah looks like your cuda version is 11.4, which is not compatible. can you upgrade your cuda version to the 11.8/12.1/12.4?

**Comment by abearab** [comment]
@HenryCarr98 I had some luck installing KGWAS by installing dependencies through conda, see #1. Maybe that helps?

**Comment by HenryCarr98** [comment]
Hello @abearab and thanks for your message. Could you just confirm how exactly you did that?

**Comment by abearab** [comment]
you may start with this:

```bash
conda env create -f https://raw.githubusercontent.com/abearab/KGWAS/refs/heads/master/environment.yml
```

**Comment by HenryCarr98** [comment]
Ah great, looks good thank you. Does this fix help with the CUDA compatibility issues? Cheers

**Comment by abearab** [comment]
> Ah great, looks good thank you. Does this fix help with the CUDA compatibility issues? Cheers

Hopefully! The goal is conda will try to install compatible versions of these dependencies including `torch_sparse`. I don't have access to a CUDA GPU at the moment to test it myself. You can give it a try.

**Comment by HenryCarr98** [comment]
Perfect, I'll give this a try. I'll let you know what the results are. Cheers and happy new year!

**Comment by kexinhuang12345** [comment]
Thanks for the help @abearab ! Yes, if conda does not work, i would suggest contacting the HPC cluster admin; usually they have alternative cuda versions supported and they can help you load the module. It should be a common request as cuda version changes a lot.

**Comment by kexinhuang12345** [comment]
@HenryCarr98 is it working? if so, please close the issue - thanks!

**Comment by HenryCarr98** [comment]
Hi sorry I forgot to answer. Yes all working thanks!!
